# Generated by Django 5.1.6 on 2025-05-10 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="pictures/seller"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=10,
                        null=True,
                        unique=True,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False, editable=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BuyerVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aadhaar_card",
                    models.ImageField(upload_to="pictures/seller/verification/aadhaar"),
                ),
                (
                    "aadhaar_number",
                    models.BigIntegerField(
                        editable=False,
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1000000000000),
                            django.core.validators.MaxValueValidator(9999999999999),
                        ],
                    ),
                ),
                (
                    "pan_card",
                    models.ImageField(upload_to="pictures/seller/verification/pan"),
                ),
                (
                    "pan_number",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
