# Generated by Django 5.2.2 on 2025-07-10 09:54

import common.models
import common.utils.storage_backends
import django.core.validators
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=common.utils.storage_backends.MediaStorage,
                        upload_to=functools.partial(
                            common.models.get_user_document_upload_path,
                            *(),
                            **{"subfolder": "profile_pictures"}
                        ),
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=10,
                        null=True,
                        unique=True,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False, editable=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BuyerVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aadhaar_card",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=common.utils.storage_backends.MediaStorage,
                        upload_to=functools.partial(
                            common.models.get_user_document_upload_path,
                            *(),
                            **{"subfolder": "verification/aadhaar_card"}
                        ),
                    ),
                ),
                (
                    "aadhaar_number",
                    models.BigIntegerField(
                        editable=False,
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1000000000000),
                            django.core.validators.MaxValueValidator(9999999999999),
                        ],
                    ),
                ),
                (
                    "pan_card",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=common.utils.storage_backends.MediaStorage,
                        upload_to=functools.partial(
                            common.models.get_user_document_upload_path,
                            *(),
                            **{"subfolder": "verification/pan_card"}
                        ),
                    ),
                ),
                (
                    "pan_number",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PurchasedEstate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_date", models.DateTimeField(auto_now_add=True)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["-purchase_date"],
            },
        ),
        migrations.CreateModel(
            name="WishlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-added_on"],
            },
        ),
    ]
