# Generated by Django 5.2.2 on 2025-07-10 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buyer_data", "0001_initial"),
        ("estate_data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="buyerverification",
            name="buyer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyerverification",
                to="buyer_data.buyer",
            ),
        ),
        migrations.AddField(
            model_name="purchasedestate",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchased_estates",
                to="buyer_data.buyer",
            ),
        ),
        migrations.AddField(
            model_name="purchasedestate",
            name="estate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchased_by",
                to="estate_data.estate",
            ),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlistitems",
                to="buyer_data.buyer",
            ),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="estate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlisted_by",
                to="estate_data.estate",
            ),
        ),
        migrations.AddIndex(
            model_name="purchasedestate",
            index=models.Index(
                fields=["buyer", "purchase_date"], name="buyer_data__buyer_i_761eee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasedestate",
            index=models.Index(
                fields=["estate", "purchase_date"],
                name="buyer_data__estate__eb95ba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="purchasedestate",
            index=models.Index(
                fields=["transaction_id"], name="buyer_data__transac_405d12_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="purchasedestate",
            unique_together={("buyer", "estate")},
        ),
        migrations.AddIndex(
            model_name="wishlistitem",
            index=models.Index(
                fields=["buyer", "added_on"], name="buyer_data__buyer_i_ea08b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wishlistitem",
            index=models.Index(
                fields=["estate", "added_on"], name="buyer_data__estate__1daca6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wishlistitem",
            unique_together={("buyer", "estate")},
        ),
    ]
