# Generated by Django 5.1.6 on 2025-04-03 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyerverification",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="buyer_data.buyer"
            ),
        ),
    ]
