# Generated by Django 5.1.6 on 2025-05-14 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buyer_data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="buyerverification",
            name="buyer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyerverification",
                to="buyer_data.buyer",
            ),
        ),
    ]
