# Generated by Django 5.2.1 on 2025-06-14 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer_data", "0002_initial"),
        ("estate_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WishlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlistitems",
                        to="buyer_data.buyer",
                    ),
                ),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlisted_by",
                        to="estate_data.estate",
                    ),
                ),
            ],
            options={
                "ordering": ["-added_on"],
                "indexes": [
                    models.Index(
                        fields=["buyer", "added_on"],
                        name="buyer_data__buyer_i_ea08b7_idx",
                    ),
                    models.Index(
                        fields=["estate", "added_on"],
                        name="buyer_data__estate__1daca6_idx",
                    ),
                ],
                "unique_together": {("buyer", "estate")},
            },
        ),
    ]
