# Generated by Django 5.1.6 on 2025-04-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer_data", "0002_alter_buyerverification_buyer"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
