# Generated by Django 5.2.2 on 2025-07-10 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buyer_data", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PurchasedEstate",
        ),
    ]
