# Generated by Django 5.1.6 on 2025-04-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer_data", "0003_buyer_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="phone_number",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
