# Generated by Django 5.2.2 on 2025-07-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer_data", "0003_delete_purchasedestate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="phone_number",
            field=models.IntegerField(
                default=1, editable=False, max_length=10, unique=True
            ),
            preserve_default=False,
        ),
    ]
