# Generated by Django 5.2.2 on 2025-06-15 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer_data", "0003_wishlistitem"),
        ("estate_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchasedEstate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_date", models.DateTimeField(auto_now_add=True)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "transaction_id",
                    models.CharField(editable=False, max_length=100, unique=True),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchased_estates",
                        to="buyer_data.buyer",
                    ),
                ),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchased_by",
                        to="estate_data.estate",
                    ),
                ),
            ],
            options={
                "ordering": ["-purchase_date"],
                "indexes": [
                    models.Index(
                        fields=["buyer", "purchase_date"],
                        name="buyer_data__buyer_i_761eee_idx",
                    ),
                    models.Index(
                        fields=["estate", "purchase_date"],
                        name="buyer_data__estate__eb95ba_idx",
                    ),
                    models.Index(
                        fields=["transaction_id"], name="buyer_data__transac_405d12_idx"
                    ),
                ],
                "unique_together": {("buyer", "estate")},
            },
        ),
    ]
