# Generated by Django 5.2.2 on 2025-07-12 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer_data", "0004_alter_buyer_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="phone_number",
            field=models.IntegerField(
                editable=False,
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(1000000000),
                    django.core.validators.MaxValueValidator(9999999999),
                ],
            ),
        ),
    ]
