# Generated by Django 5.1.6 on 2025-04-09 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer_data", "0004_alter_buyer_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="phone_number",
            field=models.CharField(
                blank=True, editable=False, max_length=10, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="buyerverification",
            name="buyer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="buyer_data.buyer"
            ),
        ),
    ]
