# Generated by Django 5.2.2 on 2025-06-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer_data", "0004_purchasedestate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasedestate",
            name="transaction_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
