# Generated by Django 5.2.2 on 2025-07-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buyer_data", "0005_alter_buyer_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buyer",
            name="is_deleted",
        ),
    ]
