# Generated by Django 5.1.6 on 2025-04-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer_data", "0005_alter_buyer_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyerverification",
            name="aadhaar_card",
            field=models.ImageField(upload_to="pictures/seller/verification/aadhaar"),
        ),
        migrations.AlterField(
            model_name="buyerverification",
            name="pan_card",
            field=models.ImageField(upload_to="pictures/seller/verification/pan"),
        ),
    ]
