# Generated by Django 5.1.6 on 2025-05-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer_data", "0006_alter_buyerverification_aadhaar_card_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="buyer",
            options={},
        ),
        migrations.AlterModelManagers(
            name="buyer",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="buyer",
            name="user_ptr",
        ),
        migrations.AddField(
            model_name="buyer",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
