# Generated by Django 5.1.6 on 2025-05-11 06:05

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="pictures/seller"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=10,
                        null=True,
                        unique=True,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False, editable=False)),
                ("business_name", models.CharField(editable=False, max_length=100)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user", models.Model),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="SellerVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aadhaar_card",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pictures/seller/verification/aadhaar",
                    ),
                ),
                (
                    "aadhaar_number",
                    models.BigIntegerField(
                        editable=False,
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1000000000000),
                            django.core.validators.MaxValueValidator(9999999999999),
                        ],
                    ),
                ),
                (
                    "pan_card",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pictures/seller/verification/pan",
                    ),
                ),
                (
                    "pan_number",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                (
                    "agent_rera_id",
                    models.CharField(editable=False, max_length=12, unique=True),
                ),
                (
                    "gstin",
                    models.BigIntegerField(
                        editable=False,
                        unique=True,
                        validators=[
                            django.core.validators.MaxValueValidator(9999999999)
                        ],
                    ),
                ),
                (
                    "seller",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seller_data.seller",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
