# Generated by Django 5.2.2 on 2025-07-10 09:54

import common.models
import common.utils.storage_backends
import django.core.validators
import django.db.models.deletion
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=common.utils.storage_backends.MediaStorage,
                        upload_to=functools.partial(
                            common.models.get_user_document_upload_path,
                            *(),
                            **{"subfolder": "profile_pictures"}
                        ),
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=10,
                        null=True,
                        unique=True,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False, editable=False)),
                ("business_name", models.CharField(editable=False, max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SellerSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("1", "Stage 1 - Basic"),
                            ("2", "Stage 2 - Standard"),
                            ("3", "Stage 3 - Premium"),
                            ("4", "Stage 4 - Ultimate"),
                        ],
                        default="1",
                        max_length=5,
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "seller",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="seller_data.seller",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SellerVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aadhaar_card",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=common.utils.storage_backends.MediaStorage,
                        upload_to=functools.partial(
                            common.models.get_user_document_upload_path,
                            *(),
                            **{"subfolder": "verification/aadhaar_card"}
                        ),
                    ),
                ),
                (
                    "aadhaar_number",
                    models.BigIntegerField(
                        editable=False,
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1000000000000),
                            django.core.validators.MaxValueValidator(9999999999999),
                        ],
                    ),
                ),
                (
                    "pan_card",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=common.utils.storage_backends.MediaStorage,
                        upload_to=functools.partial(
                            common.models.get_user_document_upload_path,
                            *(),
                            **{"subfolder": "verification/pan_card"}
                        ),
                    ),
                ),
                (
                    "pan_number",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                (
                    "agent_rera_id",
                    models.CharField(editable=False, max_length=12, unique=True),
                ),
                (
                    "gstin",
                    models.BigIntegerField(
                        editable=False,
                        unique=True,
                        validators=[
                            django.core.validators.MaxValueValidator(9999999999)
                        ],
                    ),
                ),
                (
                    "seller",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seller_data.seller",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
