# Generated by Django 5.2.2 on 2025-07-20 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seller_data", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sellerverification",
            name="aadhaar_card",
        ),
        migrations.RemoveField(
            model_name="sellerverification",
            name="aadhaar_number",
        ),
    ]
