# Generated by Django 5.1.6 on 2025-04-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
