# Generated by Django 5.2.2 on 2025-06-25 08:03

import common.models
import common.utils.storage_backends
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=common.utils.storage_backends.MediaStorage,
                upload_to=functools.partial(
                    common.models.get_user_document_upload_path,
                    *(),
                    **{"subfolder": "profile_pictures"}
                ),
            ),
        ),
        migrations.AlterField(
            model_name="sellerverification",
            name="aadhaar_card",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=common.utils.storage_backends.MediaStorage,
                upload_to=functools.partial(
                    common.models.get_user_document_upload_path,
                    *(),
                    **{"subfolder": "verification/aadhaar_card"}
                ),
            ),
        ),
        migrations.AlterField(
            model_name="sellerverification",
            name="pan_card",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=common.utils.storage_backends.MediaStorage,
                upload_to=functools.partial(
                    common.models.get_user_document_upload_path,
                    *(),
                    **{"subfolder": "verification/pan_card"}
                ),
            ),
        ),
    ]
