# Generated by Django 5.1.6 on 2025-04-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller_data", "0002_seller_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="business_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="seller",
            name="phone_number",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
