# Generated by Django 5.2.2 on 2025-07-04 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller_data", "0002_alter_seller_profile_picture_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("1", "Stage 1 - Basic"),
                            ("2", "Stage 2 - Standard"),
                            ("3", "Stage 3 - Premium"),
                            ("4", "Stage 4 - Ultimate"),
                        ],
                        default="1",
                        max_length=2,
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "seller",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="seller_data.seller",
                    ),
                ),
            ],
        ),
    ]
