# Generated by Django 5.2.2 on 2025-07-30 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller_data", "0002_remove_sellerverification_aadhaar_card_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="phone_number",
            field=models.BigIntegerField(
                editable=False,
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(1000000000),
                    django.core.validators.MaxValueValidator(9999999999),
                ],
            ),
        ),
    ]
