# Generated by Django 5.2.2 on 2025-07-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seller_data", "0003_alter_seller_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seller",
            name="is_deleted",
        ),
    ]
