# Generated by Django 5.1.6 on 2025-04-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller_data", "0003_alter_seller_business_name_alter_seller_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="business_name",
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name="seller",
            name="phone_number",
            field=models.CharField(
                blank=True, editable=False, max_length=10, null=True, unique=True
            ),
        ),
    ]
