# Generated by Django 5.2.2 on 2025-07-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller_data", "0003_sellersubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellersubscription",
            name="stage",
            field=models.CharField(
                choices=[
                    ("1", "Stage 1 - Basic"),
                    ("2", "Stage 2 - Standard"),
                    ("3", "Stage 3 - Premium"),
                    ("4", "Stage 4 - Ultimate"),
                ],
                default="1",
                max_length=5,
            ),
        ),
    ]
