# Generated by Django 5.1.6 on 2025-04-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller_data", "0004_alter_seller_business_name_alter_seller_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerverification",
            name="aadhaar_card",
            field=models.ImageField(upload_to="pictures/seller/verification/aadhaar"),
        ),
        migrations.AlterField(
            model_name="sellerverification",
            name="pan_card",
            field=models.ImageField(upload_to="pictures/seller/verification/pan"),
        ),
    ]
