# Generated by Django 5.1.6 on 2025-04-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller_data", "0005_alter_sellerverification_aadhaar_card_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerverification",
            name="agent_rera_id",
            field=models.CharField(
                default=1, editable=False, max_length=12, unique=True
            ),
            preserve_default=False,
        ),
    ]
