# Generated by Django 5.1.6 on 2025-05-04 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller_data", "0006_sellerverification_agent_rera_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seller",
            options={},
        ),
        migrations.AlterModelManagers(
            name="seller",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="seller",
            name="user_ptr",
        ),
        migrations.AddField(
            model_name="seller",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seller",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seller_profile",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
