# Generated by Django 5.1.6 on 2025-03-28 19:23

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="pictures/buyer"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=10,
                        null=True,
                        unique=True,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False, editable=False)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="pictures/seller"
                    ),
                ),
                ("business_name", models.CharField(editable=False, max_length=100)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=10,
                        null=True,
                        unique=True,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False, editable=False)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Estate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="pictures/estate"
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("address", models.CharField(editable=False, max_length=120)),
                ("pricing", models.FloatField(editable=False)),
                ("description", models.TextField()),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.seller"
                    ),
                ),
            ],
        ),
    ]
