# Generated by Django 5.1.6 on 2025-03-28 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aadhaar_card",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pictures/seller/verification/aadhaar",
                    ),
                ),
                (
                    "aadhaar_number",
                    models.IntegerField(editable=False, max_length=12, unique=True),
                ),
                (
                    "pam_card",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pictures/seller/verification/pan",
                    ),
                ),
                (
                    "pan_number",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuyerVerification",
            fields=[
                (
                    "verificationdetails_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.verificationdetails",
                    ),
                ),
                (
                    "buyer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.buyer"
                    ),
                ),
            ],
            bases=("api.verificationdetails",),
        ),
        migrations.CreateModel(
            name="SellerVerification",
            fields=[
                (
                    "verificationdetails_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.verificationdetails",
                    ),
                ),
                (
                    "gstin",
                    models.IntegerField(editable=False, max_length=15, unique=True),
                ),
                (
                    "seller",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.seller"
                    ),
                ),
            ],
            bases=("api.verificationdetails",),
        ),
    ]
