# Generated by Django 5.1.6 on 2025-03-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="estate",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="pictures/estate"),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="pictures/buyer"),
        ),
        migrations.AlterField(
            model_name="seller",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="pictures/seller"),
        ),
    ]
