# Generated by Django 5.1.6 on 2025-03-28 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_verificationdetails_buyerverification_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="verificationdetails",
            old_name="pam_card",
            new_name="pan_card",
        ),
        migrations.AlterField(
            model_name="sellerverification",
            name="gstin",
            field=models.IntegerField(
                editable=False,
                unique=True,
                validators=[django.core.validators.MaxValueValidator(9999999999)],
            ),
        ),
        migrations.AlterField(
            model_name="verificationdetails",
            name="aadhaar_number",
            field=models.IntegerField(
                editable=False,
                unique=True,
                validators=[django.core.validators.MaxValueValidator(999999999999)],
            ),
        ),
    ]
