# Generated by Django 5.1.6 on 2025-03-31 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_pam_card_verificationdetails_pan_card_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerverification",
            name="gstin",
            field=models.BigIntegerField(
                editable=False,
                unique=True,
                validators=[django.core.validators.MaxValueValidator(9999999999)],
            ),
        ),
        migrations.AlterField(
            model_name="verificationdetails",
            name="aadhaar_number",
            field=models.BigIntegerField(
                editable=False,
                unique=True,
                validators=[django.core.validators.MaxValueValidator(999999999999)],
            ),
        ),
    ]
