# Generated by Django 5.2.2 on 2025-07-17 06:37

import common.utils.storage_backends
import django.db.models.deletion
import estate_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("seller_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estate_government_id",
                    models.CharField(db_index=True, max_length=13, unique=True),
                ),
                ("estate_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "estate_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("house", "House"),
                            ("land", "Land"),
                            ("commercial", "Commercial"),
                            ("villa", "Villa"),
                            ("townhouse", "Townhouse"),
                            ("duplex", "Duplex"),
                            ("studio", "Studio"),
                            ("penthouse", "Penthouse"),
                            ("cottage", "Cottage"),
                        ],
                        max_length=255,
                    ),
                ),
                ("estate_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("sold", "Sold"),
                            ("rented", "Rented"),
                            ("pending", "Pending"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=255, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seller_data.seller",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstateImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        storage=common.utils.storage_backends.MediaStorage,
                        upload_to=estate_data.models.estate_image_path,
                    ),
                ),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        related_query_name="image",
                        to="estate_data.estate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstateMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("views", models.IntegerField(default=0, editable=False)),
                ("bookmarks", models.IntegerField(default=0, editable=False)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "estate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        related_query_name="view",
                        to="estate_data.estate",
                    ),
                ),
            ],
        ),
    ]
