# Generated by Django 5.1.6 on 2025-04-22 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("seller_data", "0005_alter_sellerverification_aadhaar_card_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estate_name", models.CharField(max_length=255)),
                (
                    "estate_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("house", "House"),
                            ("land", "Land"),
                            ("commercial", "Commercial"),
                            ("villa", "Villa"),
                            ("townhouse", "Townhouse"),
                            ("duplex", "Duplex"),
                            ("studio", "Studio"),
                            ("penthouse", "Penthouse"),
                            ("cottage", "Cottage"),
                        ],
                        max_length=255,
                    ),
                ),
                ("estate_price", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("sold", "Sold"),
                            ("rented", "Rented"),
                            ("pending", "Pending"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seller_data.seller",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstateImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="pictures/estate_images/")),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        related_query_name="image",
                        to="estate_data.estate",
                    ),
                ),
            ],
        ),
    ]
