# Generated by Django 5.2.2 on 2025-06-24 09:33

import estate_data.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estate_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estateimage",
            name="image",
            field=models.ImageField(
                storage=storages.backends.s3.S3Storage,
                upload_to=estate_data.models.estate_image_path,
            ),
        ),
    ]
