# Generated by Django 5.1.6 on 2025-04-22 03:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estate_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="estate",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=1, geography=True, srid=4326
            ),
            preserve_default=False,
        ),
    ]
