# Generated by Django 5.1.6 on 2025-05-11 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estate_data", "0001_initial"),
        ("seller_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="estate",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="seller_data.seller"
            ),
        ),
        migrations.AddField(
            model_name="estateimage",
            name="estate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                related_query_name="image",
                to="estate_data.estate",
            ),
        ),
    ]
