# Generated by Django 5.1.6 on 2025-04-22 23:29

import estate_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estate_data", "0002_estate_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="estate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="estate",
            name="slug",
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="estate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="estate",
            name="estate_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="estateimage",
            name="image",
            field=models.ImageField(upload_to=estate_data.models.estate_image_path),
        ),
    ]
