# Generated by Django 5.1.6 on 2025-05-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estate_data", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estate",
            name="latitude",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
        migrations.AlterField(
            model_name="estate",
            name="longitude",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
    ]
