# Generated by Django 5.2.2 on 2025-06-25 08:03

import common.utils.storage_backends
import estate_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estate_data", "0002_alter_estateimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estateimage",
            name="image",
            field=models.ImageField(
                storage=common.utils.storage_backends.MediaStorage,
                upload_to=estate_data.models.estate_image_path,
            ),
        ),
    ]
