# Generated by Django 5.2.2 on 2025-06-29 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estate_data", "0003_alter_estateimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="estate",
            name="estate_government_id",
            field=models.CharField(
                db_index=True, default=1, max_length=255, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="estate",
            name="slug",
            field=models.SlugField(
                blank=True, editable=False, max_length=255, unique=True
            ),
        ),
        migrations.CreateModel(
            name="EstateViews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("views", models.IntegerField(default=0, editable=False)),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        related_query_name="view",
                        to="estate_data.estate",
                    ),
                ),
            ],
        ),
    ]
