# Generated by Django 5.2.2 on 2025-06-30 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estate_data", "0004_estate_estate_government_id_alter_estate_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estateviews",
            name="estate",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                related_query_name="view",
                to="estate_data.estate",
            ),
        ),
    ]
