# Generated by Django 5.2.2 on 2025-07-01 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estate_data", "0005_alter_estateviews_estate"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EstateViews",
            new_name="EstateMetrics",
        ),
    ]
