# Generated by Django 5.2.2 on 2025-07-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estate_data", "0006_rename_estateviews_estatemetrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="estatemetrics",
            name="bookmarks",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="estatemetrics",
            name="likes",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
