# Generated by Django 5.2.2 on 2025-07-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estate_data", "0007_estatemetrics_bookmarks_estatemetrics_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estatemetrics",
            name="likes",
        ),
    ]
