# Generated by Django 5.2.2 on 2025-07-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estate_data", "0008_remove_estatemetrics_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="estatemetrics",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
