# Generated by Django 5.2.2 on 2025-07-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estate_data", "0009_estatemetrics_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="estate",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
