# Generated by Django 5.2.2 on 2025-07-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estate_data", "0010_estate_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estate",
            name="estate_government_id",
            field=models.CharField(db_index=True, max_length=13, unique=True),
        ),
    ]
